# Generated by Django 3.0.6 on 2020-07-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='filesize',
        ),
    ]
