# Generated by Django 3.0.6 on 2020-07-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500)),
                ('filesize', models.CharField(max_length=200)),
                ('extension', models.CharField(max_length=200)),
            ],
        ),
    ]
